### ISSUE TITLE
Vertical title bar is not visible on iOS

### ISSUE THREAD

**Issue by spencewenski** [dracula/obsidian#11]
Hello,

I am trying to use this theme on iOS, but the vertical title is not visible (screenshot below). I installed the theme using the Obsidian settings UI. I see the same behavior on both my phone and my iPad.

Devices: iPhone 13 mini (iOS 15.1.1) and iPad Pro (iOS 15.1)
Obsidian version: 1.0.5

![screenshot](https://user-images.githubusercontent.com/3319370/147610181-aefeb58d-17e5-4999-b30e-344f2c8efeba.png)

**Comment by Chrismettal** [comment]
Vertical titlebar has since been completely removed and would need to be reimplemented after the upcoming 0.16 UI update. Original titlebar should now work as expected on iOS.
