### ISSUE TITLE
Horizontal title bar

### ISSUE THREAD

**Issue by spencewenski** [dracula/obsidian#12]
Hello,

I would prefer to have a normal horizontal title bar. Is it possible to switch the title bar back to horizontal? Or could you provide two different versions of the theme somehow, one with a horizontal title bar and one with a vertical title bar?

Thanks.

**Comment by kjharcombe** [comment]
@spencewenski, I found myself with the same issue. I have found a temporary fix by removing lines 260 to 417 from the obsidian.css file. I've also opened a pull request - #13 - with my changes.
Hope this helps 😃

**Comment by JordanTheITGuy** [comment]
I second this, that or address the code in such a way that a simple comment to the CSS can turn the whole section on or off. It's also worth noting that because of how the bar is reshaped that if you go back to horizontal the sizing's of the bar are not quite right anymore.

**Comment by Chrismettal** [comment]
Totally agree, especially with the 0.16 UI changes coming around, the vertical bar will most likely no longer work anyways. After the redesign we could try reimplementing optionally if this was a desired feature.
