### ISSUE TITLE
Usage of <> issue

### ISSUE THREAD

**Issue by thomasbruchet** [dracula/obsidian#14]
Hello

When I use <> to inform about a variable in a cmd line I've an issue on the GUI. 
If I write this I've no issue in the GUI.
> Test SNMP:  snmpwalk -v 2c -c public IP
![image](https://user-images.githubusercontent.com/86605223/149536125-c231c23d-bca0-4813-b006-94383c885bae.png)

But If I write this with <> on left and right of the variable IP, I've a problem on all become after. 
> Test SNMP:  snmpwalk -v 2c -c public <IP>
![image](https://user-images.githubusercontent.com/86605223/149536304-af6c3728-3643-4453-a822-48c09e4bb14f.png)
And If I change the current view from edit to reading, the <IP> is not showed
![image](https://user-images.githubusercontent.com/86605223/149536371-844f7b1f-a412-421b-ad3d-e306719bd761.png)

Have you any information about that ?

**Comment by Chrismettal** [comment]
This behavior is not theme dependent and is the same without any theming in base Obsidian. You could open up an issue on their forum for this.

The Obsidian renderer tries to interpret everything starting with `<` as HTML it seems, so for example, if you not only do `<IP>` but also "close" it with `</IP>` obsidian will render correctly afterwards.
