### ISSUE TITLE
Right Click Heighlight

### ISSUE THREAD

**Issue by JordanTheITGuy** [dracula/obsidian#15]
![image](https://user-images.githubusercontent.com/32438363/151812105-959a6dd6-8a30-4731-be68-652625dbee48.png)

When you hover over any of the right click interactions there is no hover color.

**Comment by Chrismettal** [comment]
Thank you. The primary and secondary background colors were set to the same value, which also made several panes blend together that were supposed to have distinction between them. Updated now.

The secondary-alt color is still the same as the primary background color, which leads to a little bit of detail still lost, but it is more detailed than it was before.
