### ISSUE TITLE
LOOKING FOR NEW MAINTAINERS!

### ISSUE THREAD

**Issue by andybyers21** [dracula/obsidian#16]
I currently don't have time to manage this repo and am not familiar with the latest updates to Obsidian. Saying that I don't want to see it die.

Looking for a new maintainer to hand over the ropes to.

**Comment by ericjeker** [comment]
Let me dive into it a bit and I will see if I can do something. I just started using Obsidian today. Also there is currently 2 or 3 Dracula themes in Obsidian, this is pretty confusing.

**Comment by chillfox** [comment]
One of the other themes makes some odd text/background colour choices that make some things like the notifications almost unreadable.

**Comment by Chrismettal** [comment]
Hey,

has a maintainer been chosen yet?

In addition to the already open PRs that could be merged quickly, current versions of Obsidian seem to dislike it, when the font family and size is chosen inside a theme. 
For the [Behave Theme](https://github.com/Chrismettal/Obsidian-Behave-dark) I fully removed all font-family and font-size settings, allowing the interface to be scaled by Obsidian itself, as well as allow users to choose their own fonts ( #18 explains this well. Removing all font-size settings gives users the scroll scaling back)

Also, the installation instructions should be updated to reflect the new, easy installation from within Obsidians theme manager.

If a PR is opened with these changes, will someone be available to review and merge? Alternatively, can the maintainer role be passed on?

Thanks!

**Comment by luxonauta** [comment]
That is totally understandable; thank you, @andybyers21, for your contributions, passion for the project, and for opening this Issue. 💜

I've been talking to @Chrismettal, who will take over as the project's maintainer. So I'll be closing the Issue. 🧛🏻
