### ISSUE TITLE
Obisidian->Appearance->Font Size doesn't change font size (Mac, iPad, Android)

### ISSUE THREAD

**Issue by Yashigeshi** [dracula/obsidian#18]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by chillfox** [comment]
Got the same problem on Linux.
Font size does nothing.

Here's a screenshot with font size set to 30
![image](https://user-images.githubusercontent.com/12032958/169177613-9a218c82-8375-4bae-ad2a-49b6c110274e.png)

and again with it set to 10
![image](https://user-images.githubusercontent.com/12032958/169177758-3acf9f7c-b885-4370-9a03-8b41c6447509.png)

**Comment by chillfox** [comment]
I can see that font size is set to a fixed pixel size in the CSS file, so I am guessing that just needs to be some variable instead. I haven't been able to find any docs on Obsidian theme development though.

**Comment by JW2586** [comment]
Same with Windows, changing font size in settings or using `ctrl+scroll` doesn't work

**Comment by Chrismettal** [comment]
Agreed. Removed all font sizing and weighting. Thank you!
