### ISSUE TITLE
Needs to be updated to fit Obsidian's New UI.

### ISSUE THREAD

**Issue by VKEERTHIVIKRAM** [dracula/obsidian#20]
Obsidian has a new UI update and the theme needs to be updated to adapt to it, as it is already classified as a legacy theme on the theme marketplace.

**Comment by Chrismettal** [comment]
As I don't have access to the insider builds, this will have to wait until I can actually test on 0.16. 

Will probably be prepared in a separate branch blindly and debugged after wide release of 0.16.

**Comment by Chrismettal** [comment]
Migrated and removed legacy status from `obsidian-releases` 
https://github.com/obsidianmd/obsidian-releases/pull/1183
