### ISSUE TITLE
No highlighted line in the dialog box to open a file

### ISSUE THREAD

**Issue by nununo** [dracula/obsidian#22]
Hello,
The dialog box to open a file doesn't highlight any line so there is no way to know which file will open:

<img width="1120" alt="Screenshot 2022-09-26 at 12 02 35" src="https://user-images.githubusercontent.com/532049/192260743-6585645c-96fb-491d-8dec-befaf490d539.png">

**Comment by Chrismettal** [comment]
Hey,

the Dracula theme doesn't support light mode at all. If you force on light mode you will not see most of the colors set by the theme.

Also can you explain how to open that file dialog box even so I can reproduce in the dark theme? The search and file dialogs all open in the left bar for me.

**Comment by nununo** [comment]
> the Dracula theme doesn't support light mode at all. If you force on light mode you will not see most of the colors set by the theme.
Ah! I didn't know. It does make sense :) Sorry for this then. I will close the issue.

> Also can you explain how to open that file dialog box even so I can reproduce in the dark theme? The search and file dialogs all open in the left bar for me.
You can press CMD+O to open a file. a dialog box will show up where you can type parts of a filename and the matches will show below.
