### ISSUE TITLE
Plugin tag contrast issue

### ISSUE THREAD

**Issue by trijste** [dracula/obsidian#23]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![2022-10-01 - Tristan James Steiner - Obsidian v0 15 9-Obsidian-01102022-1704](https://user-images.githubusercontent.com/23725702/193428315-ff153009-c836-4850-8d0f-2faa2f9aa63a.png)

Contrast issue on that green tag when browsing plugins.

**Comment by Chrismettal** [comment]
Thanks,

that's for Obsidian versions pre 0.16, right?

**Comment by trijste** [comment]
correct

![2022-09-23 - Tristan James Steiner - Obsidian v0 15 9-Obsidian-02102022-0843](https://user-images.githubusercontent.com/23725702/193454565-485814ac-5b08-48e6-b796-fea0d6ca5345.png)

**Comment by Chrismettal** [comment]
Pushed an update. `flait.mod-pop` was missing the appropriate text color. Thanks for the find! Don't usually use plugins so I never saw this one myself.

Please check for updates in your Obsidian theme list to see this change.

![image](https://user-images.githubusercontent.com/39636046/193565816-bedb335e-f2e7-43fc-979d-6b40c5b3e7af.png)
