### ISSUE TITLE
Tag and Date Colors not working in Kanban Plugin

### ISSUE THREAD

**Issue by Leo310** [dracula/obsidian#25]
**Problem:**
Dracula Colorscheme seems to overwrite the Tag and Date colors of the Kanban Plugin.

**How it should look like (Obsidianite Colorscheme)**:
Kanban Config on Display Tag colors
![image](https://user-images.githubusercontent.com/48623649/195983159-1926f67e-2839-464b-a5b2-d1530d9fbbea.png)
**Here one tag is white and one is red**

**How it looks like with the Dracula colorscheme**:
![image](https://user-images.githubusercontent.com/48623649/195983266-5499f200-2a7b-4918-9a1b-f5c983cb0063.png)
**Here all tags are green**

**Comment by Chrismettal** [comment]
Thanks! Don't use that plugin so I never noticed. Should not overwrite your chosen colors now:

![image](https://user-images.githubusercontent.com/39636046/202788941-de75d02d-b144-4c11-9059-8624fda44476.png)

**Comment by Leo310** [comment]
Hmm now it's correctly displayed in the settings, but still not on the Kanban board itself. And the date colors are also overwritten.
