### ISSUE TITLE
Extra quotes on blockquotes

### ISSUE THREAD

**Issue by rodrigo-pedro** [dracula/obsidian#26]
### Problem

If I type a [blockquote](https://help.obsidian.md/How+to/Format+your+notes#Blockquotes) with the symbol '>' and then switch to reading mode, the block shows an extra double quote (") at the beginning of the block.

For my use case, I use the blockquotes more for highlighting key sentences, so it doesn't make sense for there to be double quotes at the beginning of the sentence. I'm not sure this is intended behavior since it opens double quotes but doesn't close them.

Live edit mode:

![imagem](https://user-images.githubusercontent.com/28206969/201497459-298633f1-5368-492b-84ee-094e5bf963a1.png)

Reading mode:

![imagem](https://user-images.githubusercontent.com/28206969/201497471-1c47196b-d5f4-4d60-96f4-1585739233b4.png)

**Comment by Chrismettal** [comment]
Agreed. Really doesn't look right does it? Removed that extra quotation mark.
