### ISSUE TITLE
Text in Settings White like Textbox Background on Obsidian Mobile

### ISSUE THREAD

**Issue by joeschmidt97** [dracula/obsidian#28]
Hello,

I am using the Dracula theme on mobile and it appears that any text entered into the search bar or any text box within the settings are white like the textbox background. It makes it impossible to see what is being typed and hard to recall what textboxes are filled with information (such as template file locations). This issue does not happen on desktop and was wondering if there's an option to tweak this as the accent color doesn't change anything. I've attached a picture of highlighted text that disappears in the text box when not highlighted.

![SmartSelect_20221227_101437_Obsidian](https://user-images.githubusercontent.com/37383290/209693016-d5454e43-e596-4f32-b99c-12bd28860005.jpg)

**Comment by Chrismettal** [comment]
Can you navigate me how to get to that search box you screenshotted? Can't seem to find it on the Android mobile version. 
All Textboxes I can find seem to be themed correctly for me on Version 1.13.2 (69)

![Screenshot_2022-12-27-17-33-35-03_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/39636046/209695228-de5e0490-2e9b-45b1-9a65-77e9a3c023f3.jpg)

**Comment by TriplEight** [comment]
I.e. in search (top left menu) and in entry fields in settings 
![Screenshot_20230115_140437_Obsidian](https://user-images.githubusercontent.com/17856421/212542497-7df953f5-2c5d-49c4-8b00-1dae9ba13053.jpg)
![Screenshot_20230115_140717_Obsidian](https://user-images.githubusercontent.com/17856421/212542500-649e016d-50a6-4828-b37a-f8cc08c74526.jpg)
![Screenshot_20230115_140758_Obsidian](https://user-images.githubusercontent.com/17856421/212542503-1b649116-8875-4168-844d-586a5daf7573.jpg)

**Comment by TriplEight** [comment]
Sigh, I guess  both reporter and I came here instead of https://github.com/jarodise/Dracula-for-Obsidian.md (because it's more popular) to report this., it indeed has this problem This can be closed.

**Comment by Chrismettal** [comment]
Thanks for confirming!

I agree, it is a bit confusing that a 2nd, non-official Dracula theme exists, though I haven't yet tried to reach out to the maintainers regarding a potential merge.
