### ISSUE TITLE
Divider randomly has different colors

### ISSUE THREAD

**Issue by Leo310** [dracula/obsidian#32]
Why does the divider randomly has a different color in preview mode? Sometimes it is dark, sometimes it is white.
![image](https://user-images.githubusercontent.com/48623649/227717598-b5f96e58-eee7-4ac9-a9fb-6ec014d73d6d.png)

Would be great if it's always dark

**Comment by Chrismettal** [comment]
Can you share the exact file that you demonstrated this on so I can try to reproduce?

**Comment by Leo310** [comment]
This happens in any .md file when using the preview mode:
![image](https://user-images.githubusercontent.com/48623649/227717771-6b303c9b-99e9-4af5-b996-f61d447291d2.png)

Here is the file:
[Divider color.md](https://github.com/dracula/obsidian/files/11068891/Divider.color.md)

**Comment by Chrismettal** [comment]
Interesting. It was supposed to be set to white for all occurences, but for me, it never showed white at all, instead falling back to the internal `hr-color` . I have just added all variants of `hr` to use the white color. Please see if it makes a difference for you.

**Comment by Leo310** [comment]
yes this did the trick :+1:
