### ISSUE TITLE
link style changes between edit and preview modes

### ISSUE THREAD

**Issue by NicholasHoff** [dracula/obsidian#33]
In edit mode (or whatever it's called), links look like this: 

![image](https://github.com/dracula/obsidian/assets/6516590/85df6c42-d441-44e7-9529-f57a9e1ad333)

but in preview mode, they look like this:

![image](https://github.com/dracula/obsidian/assets/6516590/47ff6850-c4e8-4cb8-9705-a46f22737c5b)

Is that intended? I thought I'd report it in case it's a bug.

**Comment by Chrismettal** [comment]
Can you share what version of Obsidian and OS you are running on?
For me, Links look green in both, until clicked. After a link has been visited once it switches to purple as a "visited" color for the preview (Which the edit mode won't do)

That behavior is intended, but I don't understand where the light blue color comes from for you.

**Comment by NicholasHoff** [comment]
Sorry, I should have included that in my first post. I'm on Obsidian 1.3.4, running Pop!_OS 22.04 LTS. Here's the debug info:

```
SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.3.4
	Operating system: #202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M 6.2.6-76060206-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Dracula Official v1.0.7
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Excalidraw v1.8.17
		2: Style Settings v1.0.3
```

The debug info says that I have one snippet enabled, but that's not true. I do have a snippet but it's not enabled.

Some other things I tried:
- Deleting, not just disabling, that one snippet.
- Uninstalling the Style Settings plugin.
- I checked the "visited" status and that doesn't change either. In preview mode, links always have the blue italic style, regardless of whether they've been visited.
- I also all of this in the sandbox vault.
