### ISSUE TITLE
there is no color in the exported PDF

### ISSUE THREAD

**Issue by Hugh-Zhou** [dracula/obsidian#34]
there is no color in the exported PDF, however, this issue happened suddenly，and a few days ago it was still working normally
![image](https://github.com/dracula/obsidian/assets/51262601/be235e68-0593-4db8-a5b8-0224897777d3)
![image](https://github.com/dracula/obsidian/assets/51262601/f60d6a11-e9a5-408d-9d1a-1127ffe29036)

**Comment by Hugh-Zhou** [comment]
I have found what's the action caused this issue, in version 1.2.7, there is a update says "“Export to PDF” will now always export in “light mode.”", however, our theme is only for dark mode, wo we just copy ".theme-dark" section and change name to ".theme-light",  it's not impact your apperance in the dark mode, but in light mode may be looks like weird, but it's working if you export PDF.  finally, i hope you can fix it in offical side, becasue I'm new here for front-end, for example, CSS....., LOL

**Comment by Chrismettal** [comment]
![image](https://github.com/dracula/obsidian/assets/39636046/c8dfa61f-96f9-4af3-af41-5995221452b3)

In-line code is not perfect, but rest seems to match the preview pretty well now.
