### ISSUE TITLE
Obsidian Theme

### ISSUE THREAD

**Issue by salvoza** [dracula/obsidian#43]
Is says that the Dracula theme is a legacy theme
Obsidian version: 1.6.2
Windows 11 Pro

![image](https://github.com/dracula/obsidian/assets/9552431/f18ee441-535a-4ddf-a69d-13d54e825d8a)
![image](https://github.com/dracula/obsidian/assets/9552431/ad22bc0a-6408-406f-bfb2-7d3d3d1e4bb8)
![image](https://github.com/dracula/obsidian/assets/9552431/91218df0-d4a2-4ba3-84b3-b1ca2c9dd985)

**Comment by Chrismettal** [comment]
That's a different theme.

This repo is for the "Dracula Official" Theme

![image](https://github.com/dracula/obsidian/assets/39636046/d667fba0-b240-4ba9-804d-f7b6245be110)
