### ISSUE TITLE
Not in Theme Shop Anymore?

### ISSUE THREAD

**Issue by 1Bishop** [dracula/obsidian#44]
Sorry for this, maybe i'm missing something but i don't see the theme in the community themes anymore?
![image](https://github.com/dracula/obsidian/assets/8958725/5460967e-7377-4e3e-9c89-3452efc8b74f)

**Comment by Chrismettal** [comment]
![image](https://github.com/dracula/obsidian/assets/39636046/7c16ab79-e5ff-4a99-be59-a7fdacebc3d8)

It's definitely still there, along with many others. Which version of Obsidian are you using? Looks like you're missing the "Dark theme only" button, which might mean you are running an outdated version potentially?

**Comment by jsappl** [comment]
@1Bishop experiencing the same issue here

![theme](https://github.com/dracula/obsidian/assets/10909765/10a1d681-403b-423d-a86d-3870487fe1df)

I'm running version `1.6.3-1` on Wayland. Weird, it's still listed in the [community-css-themes.json](https://github.com/obsidianmd/obsidian-releases/blob/8eb873a1b6a3fdeab371993634ad48680437b78d/community-css-themes.json#L635)

**Comment by quarkquartet** [comment]
Same here.

And which one should we use if we find it? The 'dracula for obsidian' or 'dracula official'?

**Comment by Chrismettal** [comment]
Can you try switching off "Adapt to system" so you can see the dark/light theme only switch again? Might be a bug on Obsidian's end, not even showing dark themes when your system is detected as being light themed.

![image](https://github.com/dracula/obsidian/assets/39636046/1bb78c3f-744b-4b5d-b0cc-d829bb8af206)


This is from the Obsidian 1.6.2 changelog and suggests a breaking change in the theme searcher:

![image](https://github.com/dracula/obsidian/assets/39636046/3c7813a6-f327-41cb-a0d1-76f79df489a1)

---

> And which one should we use if we find it? The 'dracula for obsidian' or 'dracula official'?

This repo here is the "Dracula Official" one by "Dracula" as highlighted in the screenshot above.

**Comment by jsappl** [comment]
Thank you @Chrismettal that did it for me :+1:

**Comment by Chrismettal** [comment]
Glad to hear, thanks for confirming.

Leaving this open for others to find for now. 
 
Seems to me that this is something to be fixed on Obsidian's side. This theme specifies a dark and a light variant so it should show up with "only dark" or "only light" regardless. Hiding it on "Adapt" makes no sense.

**Comment by 1Bishop** [comment]
Ah this did it for me, sorry I feel silly 😅
Still learning Obsidian.
