### ISSUE TITLE
emoji rendering error in preview mode

### ISSUE THREAD

**Issue by seyoatda** [dracula/obsidian#5]
this is the raw mode when I insert emoji
![image](https://user-images.githubusercontent.com/24985838/122516217-1644ee80-d041-11eb-89df-94eef2eb68fe.png)
while in the preview mode, it was rendered at a new line above.
![image](https://user-images.githubusercontent.com/24985838/122516234-1b09a280-d041-11eb-8b5b-8444ec62bc45.png)

in other themes the emoji can be rendered in the right way.

**Comment by Chrismettal** [comment]
This seems to work perfectly on my Linux and Android machines. Can you confirm that this issue is still relevant after updating the theme?

**Comment by Chrismettal** [comment]
Cannot reproduce, assuming fixed.
