### ISSUE TITLE
404: Not Found via Download Link

### ISSUE THREAD

**Issue by taqyon** [dracula/obsidian#7]
Hi! 

I'm having trouble downloading the theme archive. When I click on the link I get a message: 

>404: Not Found

Can you please fix this? 

---

**UPD:** 
- Link here: https://draculatheme.com/obsidian
- Link: https://github.com/dracula/obsidian/archive/master.zip

**Comment by jkemp814** [comment]
I can confirm this. It also doesn't work via git clone https://github.com/dracula/obsidian.git themes
Never downloads.

**Comment by Chrismettal** [comment]
Some links still pointed to the "master" branch, but the development branch has since been renamed to "main". Pushed new installation instructions just now, website should update accordingly later.
