### ISSUE TITLE
Hi, do we have Dracula theme for obsidian on iOS now

### ISSUE THREAD

**Issue by caelanyang** [dracula/obsidian#9]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by Chrismettal** [comment]
All Obsidian themes are cross platform now, so this theme will work like any other theme on any device. Just make sure to install via the Obsidian internal theme manager as described in the [installation manual](https://draculatheme.com/obsidian) (Website will update to reflect new installation manual later tonight probably)
